"""markdown and bleach

Revision ID: 0d077e2d00dc
Revises: fbc96130d5be
Create Date: 2016-08-02 11:41:45.321620

"""

# revision identifiers, used by Alembic.
revision = '0d077e2d00dc'
down_revision = 'fbc96130d5be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
